// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type History struct {
	ID             pgtype.UUID `json:"id"`
	UserAgent      string      `json:"user_agent"`
	ClientIp       string      `json:"client_ip"`
	UserID         pgtype.UUID `json:"user_id"`
	AlID           string      `json:"al_id"`
	MangadexID     string      `json:"mangadex_id"`
	CoverImage     string      `json:"cover_image"`
	Title          string      `json:"title"`
	ReadingChapter string      `json:"reading_chapter"`
	Path           string      `json:"path"`
	LastReadAt     time.Time   `json:"last_read_at"`
	CreatedAt      time.Time   `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID `json:"id"`
	FullName       string      `json:"full_name"`
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	HashedPassword string      `json:"hashed_password"`
	Role           string      `json:"role"`
	CreatedAt      time.Time   `json:"created_at"`
}
