// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteHistory(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetHistory(ctx context.Context, id pgtype.UUID) (History, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmailOrUsername(ctx context.Context, email string) (User, error)
	ListHistories(ctx context.Context, arg ListHistoriesParams) ([]History, error)
	ListHistoriesByAgent(ctx context.Context, arg ListHistoriesByAgentParams) ([]History, error)
	ListHistoriesByUserId(ctx context.Context, arg ListHistoriesByUserIdParams) ([]History, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateHistoriesToUser(ctx context.Context, arg UpdateHistoriesToUserParams) error
	UpdateHistory(ctx context.Context, arg UpdateHistoryParams) (History, error)
}

var _ Querier = (*Queries)(nil)
